//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Testing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;effectBank bankName=&quot;TestBank1&quot;&gt;&lt;effectChain chainName=&quot;TestChain1&quot;&gt;&lt;effect name=&quot;vibrate&quot;&gt;&lt;param&gt;&lt;name&gt;onMS&lt;/name&gt;&lt;value&gt;0&lt;/value&gt;&lt;/param&gt;&lt;param&gt;&lt;name&gt;offMS&lt;/name&gt;&lt;value&gt;0&lt;/value&gt;&lt;/param&gt;&lt;/effect&gt;&lt;effect name=&quot;vibrate2&quot;&gt;&lt;param&gt;&lt;name&gt;onMS&lt;/name&gt;&lt;value&gt;0&lt;/value&gt;&lt;/param&gt;&lt;param&gt;&lt;name&gt;offMS&lt;/name&gt;&lt;value&gt;0&lt;/value&gt;&lt;/param&gt;&lt;/effect&gt;&lt;/effectChain&gt;&lt;effectChain chainName=&quot;TestChain2&quot;&gt;&lt;effect name=&quot;vibrate2&quot;&gt;&lt;param&gt;&lt;name&gt;onMS&lt;/name&gt;&lt;value&gt;0&lt;/value&gt;&lt;/param&gt;&lt;param&gt;&lt;name&gt;offMS&lt;/name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestBank1 {
            get {
                return ResourceManager.GetString("TestBank1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;effectBank bankName=&quot;TestBank2&quot;&gt;&lt;effectChain chainName=&quot;TestChain2&quot;&gt;&lt;effect name=&quot;vibrate2&quot;&gt;&lt;param&gt;&lt;name&gt;onMS&lt;/name&gt;&lt;value&gt;0&lt;/value&gt;&lt;/param&gt;&lt;param&gt;&lt;name&gt;offMS&lt;/name&gt;&lt;value&gt;0&lt;/value&gt;&lt;/param&gt;&lt;/effect&gt;&lt;effect name=&quot;vibrate&quot;&gt;&lt;param&gt;&lt;name&gt;onMS&lt;/name&gt;&lt;value&gt;0&lt;/value&gt;&lt;/param&gt;&lt;param&gt;&lt;name&gt;offMS&lt;/name&gt;&lt;value&gt;0&lt;/value&gt;&lt;/param&gt;&lt;/effect&gt;&lt;/effectChain&gt;&lt;effectChain chainName=&quot;TestChain1&quot;&gt;&lt;effect name=&quot;vibrate&quot;&gt;&lt;param&gt;&lt;name&gt;onMS&lt;/name&gt;&lt;value&gt;0&lt;/value&gt;&lt;/param&gt;&lt;param&gt;&lt;name&gt;offMS&lt;/name&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestBank2 {
            get {
                return ResourceManager.GetString("TestBank2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;effectChain chainName=&quot;TestChain1&quot;&gt;&lt;effect name=&quot;vibrate&quot;&gt;&lt;param&gt;&lt;name&gt;onMS&lt;/name&gt;&lt;value&gt;0&lt;/value&gt;&lt;/param&gt;&lt;param&gt;&lt;name&gt;offMS&lt;/name&gt;&lt;value&gt;0&lt;/value&gt;&lt;/param&gt;&lt;/effect&gt;&lt;effect name=&quot;vibrate2&quot;&gt;&lt;param&gt;&lt;name&gt;onMS&lt;/name&gt;&lt;value&gt;0&lt;/value&gt;&lt;/param&gt;&lt;param&gt;&lt;name&gt;offMS&lt;/name&gt;&lt;value&gt;0&lt;/value&gt;&lt;/param&gt;&lt;/effect&gt;&lt;/effectChain&gt;.
        /// </summary>
        internal static string TestChain1 {
            get {
                return ResourceManager.GetString("TestChain1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;effectChain chainName=&quot;TestChain2&quot;&gt;&lt;effect name=&quot;vibrate2&quot;&gt;&lt;param&gt;&lt;name&gt;onMS&lt;/name&gt;&lt;value&gt;0&lt;/value&gt;&lt;/param&gt;&lt;param&gt;&lt;name&gt;offMS&lt;/name&gt;&lt;value&gt;0&lt;/value&gt;&lt;/param&gt;&lt;/effect&gt;&lt;effect name=&quot;vibrate&quot;&gt;&lt;param&gt;&lt;name&gt;onMS&lt;/name&gt;&lt;value&gt;0&lt;/value&gt;&lt;/param&gt;&lt;param&gt;&lt;name&gt;offMS&lt;/name&gt;&lt;value&gt;0&lt;/value&gt;&lt;/param&gt;&lt;/effect&gt;&lt;/effectChain&gt;.
        /// </summary>
        internal static string TestChain2 {
            get {
                return ResourceManager.GetString("TestChain2", resourceCulture);
            }
        }
        
        internal static byte[] vibrate {
            get {
                object obj = ResourceManager.GetObject("vibrate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] vibrate2 {
            get {
                object obj = ResourceManager.GetObject("vibrate2", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
